In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np

In [3]:
def to_bipolar(vec):
    print(np.array([1 if elem > 0 else -1 for elem in vec]))
    return np.array([1 if elem > 0 else -1 for elem in vec])

def hebbian_learning_rule(vectors):
    n = vectors.shape[1]
    weight_matrix = np.zeros((n, n))    
    for vec in vectors:
        weight_matrix += np.outer(vec, vec)
        
    np.fill_diagonal(weight_matrix, 0)
    print("weight_matrix",weight_matrix)
    return weight_matrix

def synchronous_update(weight_matrix, input_vector):
    return np.sign(np.dot(weight_matrix, input_vector))
def is_recall_success(weight_matrix, input_vector):
    output_vector = synchronous_update(weight_matrix, input_vector)
    return np.array_equal(input_vector, output_vector)

In [4]:
input_vectors = np.array([
        to_bipolar([0, 0, 0, 1, 1]),
        to_bipolar([0, 1, 0, 1, 0]),
        to_bipolar([0, 1, 0, 0, 1]),
        to_bipolar([0, 0, 0, 1, 1]),
    ])

[-1 -1 -1  1  1]
[-1  1 -1  1 -1]
[-1  1 -1 -1  1]
[-1 -1 -1  1  1]


In [5]:
weight_matrix = hebbian_learning_rule(input_vectors)

for i, vec in enumerate(input_vectors):
    if is_recall_success(weight_matrix, vec):
        print(f"Input vector {i+1} is successfully recalled.")
    else:
        print(f"Input vector {i+1} is not successfully recalled.")

weight_matrix [[ 0.  0.  4. -2. -2.]
 [ 0.  0.  0. -2. -2.]
 [ 4.  0.  0. -2. -2.]
 [-2. -2. -2.  0.  0.]
 [-2. -2. -2.  0.  0.]]
Input vector 1 is successfully recalled.
Input vector 2 is not successfully recalled.
Input vector 3 is not successfully recalled.
Input vector 4 is successfully recalled.
